### ISSUE TITLE
Generating CSV reports results in error -- Insufficient permissions

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/opensearch-boshrelease#128]
To reproduce, save or import a search, "Open" it, then select "Reporting" and "Generate CSV".  This results in a popup reading:

> Error generating report: Insufficient permissions. Reach out to your OpenSearch Dashboards administrator"

<img width="769" alt="image" src="https://github.com/user-attachments/assets/bc44b1cf-d624-476e-a356-c2d4843ec11d">

**Comment by markdboyd** [comment]
This is resolved, based on manual testing in production and verification from end users
