### ISSUE TITLE
Increase proxy session lifetime

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/opensearch-boshrelease#142]
Right now, the proxy is limiting sessions to 1 hour:

https://github.com/cloud-gov/opensearch-boshrelease/blob/main/jobs/opensearch-dashboards-cf-auth-proxy/spec#L37-L39

## To do
 
- [ ] Increase session timeout to 12 hours

**Comment by pburkholder** [comment]
@wz-gsa Can we make this change to a 12-hour session lifetime (please)?
