### ISSUE TITLE
Improve Logstash filter efficiency

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/opensearch-boshrelease#151]
Investigate ways to improve the efficiency of our Logstash filters by:

- Removing unneeded filters
- Replacing custom filter code with Logstash plugins
- Removing redundant filters
- Simplifying filter complexity

## Acceptance Criteria

- [x] Benchmark the ingestor throughput in produciton
- [x] Look for ways to improve base logstash filters: https://github.com/cloud-gov/opensearch-boshrelease/tree/main/src/base-logstash-filters/src/logstash-filters
- [x] Look for ways to improve CF filters: https://github.com/cloud-gov/opensearch-boshrelease/tree/main/src/cf-logstash-filters/src/logstash-filters
- [x] Deploy changes to dev
- [x] Make sure logs are still ingested and there are no errors for dropped logs
- [x] Deploy changes to stage
- [x] Deploy changes to prod

**Comment by JasonTheMain** [comment]
improvements in prod have a theoretical 2x performance increase
