### ISSUE TITLE
message field not supporting full text search for database logs

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/opensearch-boshrelease#167]
The `message` field that is created for database logs does not seem to support full-text searching

## To do

- [ ] Figure out why `message` does not support full-text search for database logs
- [ ] Apply fix
- [ ] Deploy to dev
- [ ] Deploy to stage
- [ ] Deploy to prod

**Comment by JasonTheMain** [comment]
I think this works as long as the pattern is active

**Comment by markdboyd** [comment]
Fixed via https://github.com/cloud-gov/opensearch-boshrelease/pull/172
