### ISSUE TITLE
Update logstash filters for CF app logs to work with aggregate log drain

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/opensearch-boshrelease#46]
The CF logs from the aggregate drain have a different format than the logs previously received from the firehose to syslog architecture. The new CF app log format is https://datatracker.ietf.org/doc/html/rfc5424#section-6.

We need to update the Logstash filter configuration for CF app logs to parse this format correctly and confirm that all log fields are populated properly.

## Acceptance Criteria

- [ ] Compare app logs in OpenSearch and Elasticsaerch in dev (e.g. for "allstar") and iterate on logstash filters until the parsed fields match

**Comment by JasonTheMain** [comment]
Changed app on line for testing. looks like there are some invalid characters that need to be adjusted
